In [1]:
import torch

In [2]:
print(torch.__version__)

2.2.1


In [9]:
x = torch.randn(3,3,requires_grad = True)

In [10]:
x

tensor([[-1.7619, -0.6288,  0.1679],
        [-0.9669, -1.8059,  0.7126],
        [ 0.2412,  0.5241, -0.7770]], requires_grad=True)

In [13]:
y = x.pow(2)

In [15]:
y.backward

<bound method Tensor.backward of tensor([[3.1042, 0.3954, 0.0282],
        [0.9349, 3.2612, 0.5078],
        [0.0582, 0.2747, 0.6037]], grad_fn=<PowBackward0>)>

In [16]:
x = torch.randn(5, requires_grad=True)
y = x.pow(2)
print(x.equal(y.grad_fn._saved_self))  # True
print(x is y.grad_fn._saved_self)

True
True


In [41]:
x = torch.tensor(2.0,requires_grad=True)

In [42]:
y = 2*x**3+3

In [43]:
y

tensor(19., grad_fn=<AddBackward0>)

In [44]:
print(x.grad)

None


In [45]:
z = torch.tensor(x*2+3,requires_grad=True)

/var/folders/xw/knd54pd91c7cw57n21dntvx80000gn/T/ipykernel_2480/2446788166.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.tensor(x*2+3,requires_grad=True)


In [46]:
a = torch.sigmoid(z)

In [47]:
L = (a-y)**2

In [48]:
L

tensor(324.0328, grad_fn=<PowBackward0>)

In [49]:
L.backward()

In [51]:
z.grad #this is dL/dz

tensor(-0.0328)

In [52]:
x = torch.tensor(2.0,requires_grad=True)

In [53]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x+1

In [54]:
y

tensor(63., grad_fn=<AddBackward0>)

In [55]:
y.backward()

In [57]:
x.grad

tensor(93.)

In [65]:
x = torch.tensor([[1.,2,3],
                 [3,2,1]],requires_grad=True)

In [66]:
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [67]:
y = 3*x + 2

In [68]:
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [69]:
z = 2*y**2

In [70]:
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [71]:
out = z.mean()

In [72]:
out

tensor(140., grad_fn=<MeanBackward0>)

### perform backprop using .backward() to find gradient of output wrt x

In [73]:
out.backward() #can only be done once

In [74]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])